### ISSUE TITLE
Problems building bridge (uws) on Windows

### ISSUE THREAD

**Issue by jaredthirsk** [crrobinson14/vue-rethinkdb#4]
[UPDATE: Works on Windows Subsystem for Linux - Ubuntu 18.04.1 LTS.  Good enough for me.]

Trying to install npm packages for bridge on Windows, trying through cmd.exe and Git Bash (MINGW64):

```
D:\dev\alt\vue-rethinkdb\bridge>npm install

> uws@9.14.0 install D:\dev\alt\vue-rethinkdb\bridge\node_modules\uws
> node-gyp rebuild > build_log.txt 2>&1 || exit 0


> spawn-sync@1.0.15 postinstall D:\dev\alt\vue-rethinkdb\bridge\node_modules\spawn-sync
> node postinstall

npm WARN rethinkdb-ws-bridge@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 210 packages from 145 contributors and audited 679 packages in 49.554s
found 23 vulnerabilities (3 low, 18 moderate, 2 high)
  run `npm audit fix` to fix them, or `npm audit` for details
```

bridge\node_modules\uws\build_log.txt
```
...
d:\dev\alt\vue-rethinkdb\bridge\node_modules\uws\src\http.h(31): error C2664: 'v8::MaybeLocal<v8::String> v8::String::NewFromOneByte(v8::Isolate *,const uint8_t *,v8::NewStringType,int)': cannot convert argument 3 from 'v8::String::NewStringType' to 'v8::NewStringType' (compiling source file ..\src\addon.cpp) [D:\dev\alt\vue-rethinkdb\bridge\node_modules\uws\build\uws.vcxproj]
  d:\dev\alt\vue-rethinkdb\bridge\node_modules\uws\src\http.h(31): note: Conversion to enumeration type requires an explicit cast (static_cast, C-style cast or function-style cast) (compiling source file ..\src\addon.cpp)
d:\dev\alt\vue-rethinkdb\bridge\node_modules\uws\src\http.h(42): warning C4311: 'type cast': pointer truncation from 'void *' to 'long' (compiling source file ..\src\addon.cpp) [D:\dev\alt\vue-rethinkdb\bridge\node_modules\uws\build\uws.vcxproj]
d:\dev\alt\vue-rethinkdb\bridge\node_modules\uws\src\http.h(42): warning C4302: 'type cast': truncation from 'void *' to 'long' (compiling source file ..\src\addon.cpp) [D:\dev\alt\vue-rethinkdb\bridge\node_modules\uws\build\uws.vcxproj]
d:\dev\alt\vue-rethinkdb\bridge\node_modules\uws\src\http.h(45): error C2664: 'v8::MaybeLocal<v8::String> v8::String::NewFromOneByte(v8::Isolate *,const uint8_t *,v8::NewStringType,int)': cannot convert argument 3 from 'v8::String::NewStringType' to 'v8::NewStringType' (compiling source file ..\src\addon.cpp) [D:\dev\alt\vue-rethinkdb\bridge\node_modules\uws\build\uws.vcxproj]
  d:\dev\alt\vue-rethinkdb\bridge\node_modules\uws\src\http.h(45): note: Conversion to enumeration type requires an explicit cast (static_cast, C-style cast or function-style cast) (compiling source file ..\src\addon.cpp)
d:\dev\alt\vue-rethinkdb\bridge\node_modules\uws\src\http.h(48): error C2664: 'v8::MaybeLocal<v8::String> v8::String::NewFromOneByte(v8::Isolate *,const uint8_t *,v8::NewStringType,int)': cannot convert argument 3 from 'v8::String::NewStringType' to 'v8::NewStringType' (compiling source file ..\src\addon.cpp) [D:\dev\alt\vue-rethinkdb\bridge\node_modules\uws\build\uws.vcxproj]
  d:\dev\alt\vue-rethinkdb\bridge\node_modules\uws\src\http.h(48): note: Conversion to enumeration type requires an explicit cast (static_cast, C-style cast or function-style cast) (compiling source file ..\src\addon.cpp)
d:\dev\alt\vue-rethinkdb\bridge\node_modules\uws\src\http.h(51): error C2664: 'v8::MaybeLocal<v8::String> v8::String::NewFromOneByte(v8::Isolate *,const uint8_t *,v8::NewStringType,int)': cannot convert argument 3 from 'v8::String::NewStringType' to 'v8::NewStringType' (compiling source file ..\src\addon.cpp) [D:\dev\alt\vue-rethinkdb\bridge\node_modules\uws\build\uws.vcxproj]
  d:\dev\alt\vue-rethinkdb\bridge\node_modules\uws\src\http.h(51): note: Conversion to enumeration type requires an explicit cast (static_cast, C-style cast or function-style cast) (compiling source file ..\src\addon.cpp)
d:\dev\alt\vue-rethinkdb\bridge\node_modules\uws\src\http.h(54): error C2664: 'v8::MaybeLocal<v8::String> v8::String::NewFromOneByte(v8::Isolate *,const uint8_t *,v8::NewStringType,int)': cannot convert argument 3 from 'v8::String::NewStringType' to 'v8::NewStringType' (compiling source file ..\src\addon.cpp) [D:\dev\alt\vue-rethinkdb\bridge\node_modules\uws\build\uws.vcxproj]
  d:\dev\alt\vue-rethinkdb\bridge\node_modules\uws\src\http.h(54): note: Conversion to enumeration type requires an explicit cast (static_cast, C-style cast or function-style cast) (compiling source file ..\src\addon.cpp)
d:\dev\alt\vue-rethinkdb\bridge\node_modules\uws\src\http.h(57): error C2664: 'v8::MaybeLocal<v8::String> v8::String::NewFromOneByte(v8::Isolate *,const uint8_t *,v8::NewStringType,int)': cannot convert argument 3 from 'v8::String::NewStringType' to 'v8::NewStringType' (compiling source file ..\src\addon.cpp) [D:\dev\alt\vue-rethinkdb\bridge\node_modules\uws\build\uws.vcxproj]
  d:\dev\alt\vue-rethinkdb\bridge\node_modules\uws\src\http.h(57): note: Conversion to enumeration type requires an explicit cast (static_cast, C-style cast or function-style cast) (compiling source file ..\src\addon.cpp)
d:\dev\alt\vue-rethinkdb\bridge\node_modules\uws\src\http.h(60): error C2664: 'v8::MaybeLocal<v8::String> v8::String::NewFromOneByte(v8::Isolate *,const uint8_t *,v8::NewStringType,int)': cannot convert argument 3 from 'v8::String::NewStringType' to 'v8::NewStringType' (compiling source file ..\src\addon.cpp) [D:\dev\alt\vue-rethinkdb\bridge\node_modules\uws\build\uws.vcxproj]
  d:\dev\alt\vue-rethinkdb\bridge\node_modules\uws\src\http.h(60): note: Conversion to enumeration type requires an explicit cast (static_cast, C-style cast or function-style cast) (compiling source file ..\src\addon.cpp)
d:\dev\alt\vue-rethinkdb\bridge\node_modules\uws\src\http.h(63): error C2664: 'v8::MaybeLocal<v8::String> v8::String::NewFromOneByte(v8::Isolate *,const uint8_t *,v8::NewStringType,int)': cannot convert argument 3 from 'v8::String::NewStringType' to 'v8::NewStringType' (compiling source file ..\src\addon.cpp) [D:\dev\alt\vue-rethinkdb\bridge\node_modules\uws\build\uws.vcxproj]
  d:\dev\alt\vue-rethinkdb\bridge\node_modules\uws\src\http.h(63): note: Conversion to enumeration type requires an explicit cast (static_cast, C-style cast or function-style cast) (compiling source file ..\src\addon.cpp)
d:\dev\alt\vue-rethinkdb\bridge\node_modules\uws\src\http.h(66): error C2664: 'v8::MaybeLocal<v8::String> v8::String::NewFromOneByte(v8::Isolate *,const uint8_t *,v8::NewStringType,int)': cannot convert argument 3 from 'v8::String::NewStringType' to 'v8::NewStringType' (compiling source file ..\src\addon.cpp) [D:\dev\alt\vue-rethinkdb\bridge\node_modules\uws\build\uws.vcxproj]
  d:\dev\alt\vue-rethinkdb\bridge\node_modules\uws\src\http.h(66): note: Conversion to enumeration type requires an explicit cast (static_cast, C-style cast or function-style cast) (compiling source file ..\src\addon.cpp)
d:\dev\alt\vue-rethinkdb\bridge\node_modules\uws\src\http.h(69): error C2664: 'v8::MaybeLocal<v8::String> v8::String::NewFromOneByte(v8::Isolate *,const uint8_t *,v8::NewStringType,int)': cannot convert argument 3 from 'v8::String::NewStringType' to 'v8::NewStringType' (compiling source file ..\src\addon.cpp) [D:\dev\alt\vue-rethinkdb\bridge\node_modules\uws\build\uws.vcxproj]
  d:\dev\alt\vue-rethinkdb\bridge\node_modules\uws\src\http.h(69): note: Conversion to enumeration type requires an explicit cast (static_cast, C-style cast or function-style cast) (compiling source file ..\src\addon.cpp)
d:\dev\alt\vue-rethinkdb\bridge\node_modules\uws\src\http.h(99): error C2661: 'v8::Function::NewInstance': no overloaded function takes 0 arguments (compiling source file ..\src\addon.cpp) [D:\dev\alt\vue-rethinkdb\bridge\node_modules\uws\build\uws.vcxproj]
d:\dev\alt\vue-rethinkdb\bridge\node_modules\uws\src\http.h(102): warning C4996: 'v8::ObjectTemplate::SetNamedPropertyHandler': was declared deprecated (compiling source file ..\src\addon.cpp) [D:\dev\alt\vue-rethinkdb\bridge\node_modules\uws\build\uws.vcxproj]
  c:\users\ja\.node-gyp\10.8.0\include\node\v8.h(5941): note: see declaration of 'v8::ObjectTemplate::SetNamedPropertyHandler' (compiling source file ..\src\addon.cpp)
...
d:\dev\alt\vue-rethinkdb\bridge\node_modules\uws\src\http.h(327): error C2661: 'v8::Function::NewInstance': no overloaded function takes 0 arguments (compiling source file ..\src\addon.cpp) [D:\dev\alt\vue-rethinkdb\bridge\node_modules\uws\build\uws.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\ja\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:238:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\ja\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\dev\alt\vue-rethinkdb\bridge\node_modules\uws
gyp ERR! node -v v10.8.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
```

**Comment by jaredthirsk** [comment]
Tried upgrading socketcluster:

```
$ git diff package.json
diff --git a/bridge/package.json b/bridge/package.json
index c5de064..ed8a782 100644
--- a/bridge/package.json
+++ b/bridge/package.json
@@ -18,7 +18,7 @@
     "sc-hot-reboot": "^1.0.0",
     "scc-broker-client": "^2.1.2",
     "serve-static": "^1.13.2",
-    "socketcluster": "^10.1.0",
+    "socketcluster": "^14.3.3",
     "winston": "^2.4.0"
   }
 }
```

```
D:\dev\vue-rethinkdb\bridge>npm install

> sc-uws@10.148.2 install D:\dev\vue-rethinkdb\bridge\node_modules\sc-uws
> node-gyp rebuild > build_log.txt 2>&1 || exit 0

npm WARN rethinkdb-ws-bridge@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 317 packages from 211 contributors and audited 1376 packages in 60.266s
found 0 vulnerabilities
```

bridge/node_modules/sc_uws/build_log.txt:

```
...
d:\dev\vue-rethinkdb\bridge\node_modules\sc-uws\src\http.h(31): error C2664: 'v8::MaybeLocal<v8::String> v8::String::NewFromOneByte(v8::Isolate *,const uint8_t *,v8::NewStringType,int)': cannot convert argument 3 from 'v8::String::NewStringType' to 'v8::NewStringType' (compiling source file ..\src\addon.cpp) [D:\dev\vue-rethinkdb\bridge\node_modules\sc-uws\build\uws.vcxproj]
  d:\dev\vue-rethinkdb\bridge\node_modules\sc-uws\src\http.h(31): note: Conversion to enumeration type requires an explicit cast (static_cast, C-style cast or function-style cast) (compiling source file ..\src\addon.cpp)
d:\dev\vue-rethinkdb\bridge\node_modules\sc-uws\src\http.h(42): warning C4311: 'type cast': pointer truncation from 'void *' to 'long' (compiling source file ..\src\addon.cpp) [D:\dev\vue-rethinkdb\bridge\node_modules\sc-uws\build\uws.vcxproj]
d:\dev\vue-rethinkdb\bridge\node_modules\sc-uws\src\http.h(42): warning C4302: 'type cast': truncation from 'void *' to 'long' (compiling source file ..\src\addon.cpp) [D:\dev\vue-rethinkdb\bridge\node_modules\sc-uws\build\uws.vcxproj]
d:\dev\vue-rethinkdb\bridge\node_modules\sc-uws\src\http.h(45): error C2664: 'v8::MaybeLocal<v8::String> v8::String::NewFromOneByte(v8::Isolate *,const uint8_t *,v8::NewStringType,int)': cannot convert argument 3 from 'v8::String::NewStringType' to 'v8::NewStringType' (compiling source file ..\src\addon.cpp) [D:\dev\vue-rethinkdb\bridge\node_modules\sc-uws\build\uws.vcxproj]
  d:\dev\vue-rethinkdb\bridge\node_modules\sc-uws\src\http.h(45): note: Conversion to enumeration type requires an explicit cast (static_cast, C-style cast or function-style cast) (compiling source file ..\src\addon.cpp)
d:\dev\vue-rethinkdb\bridge\node_modules\sc-uws\src\http.h(48): error C2664: 'v8::MaybeLocal<v8::String> v8::String::NewFromOneByte(v8::Isolate *,const uint8_t *,v8::NewStringType,int)': cannot convert argument 3 from 'v8::String::NewStringType' to 'v8::NewStringType' (compiling source file ..\src\addon.cpp) [D:\dev\vue-rethinkdb\bridge\node_modules\sc-uws\build\uws.vcxproj]
  d:\dev\vue-rethinkdb\bridge\node_modules\sc-uws\src\http.h(48): note: Conversion to enumeration type requires an explicit cast (static_cast, C-style cast or function-style cast) (compiling source file ..\src\addon.cpp)
d:\dev\vue-rethinkdb\bridge\node_modules\sc-uws\src\http.h(51): error C2664: 'v8::MaybeLocal<v8::String> v8::String::NewFromOneByte(v8::Isolate *,const uint8_t *,v8::NewStringType,int)': cannot convert argument 3 from 'v8::String::NewStringType' to 'v8::NewStringType' (compiling source file ..\src\addon.cpp) [D:\dev\vue-rethinkdb\bridge\node_modules\sc-uws\build\uws.vcxproj]
  d:\dev\vue-rethinkdb\bridge\node_modules\sc-uws\src\http.h(51): note: Conversion to enumeration type requires an explicit cast (static_cast, C-style cast or function-style cast) (compiling source file ..\src\addon.cpp)
d:\dev\vue-rethinkdb\bridge\node_modules\sc-uws\src\http.h(54): error C2664: 'v8::MaybeLocal<v8::String> v8::String::NewFromOneByte(v8::Isolate *,const uint8_t *,v8::NewStringType,int)': cannot convert argument 3 from 'v8::String::NewStringType' to 'v8::NewStringType' (compiling source file ..\src\addon.cpp) [D:\dev\vue-rethinkdb\bridge\node_modules\sc-uws\build\uws.vcxproj]
  d:\dev\vue-rethinkdb\bridge\node_modules\sc-uws\src\http.h(54): note: Conversion to enumeration type requires an explicit cast (static_cast, C-style cast or function-style cast) (compiling source file ..\src\addon.cpp)
...
...

Running npm start:
```
D:\dev\vue-rethinkdb\bridge>npm start

> rethinkdb-ws-bridge@1.0.0 start D:\dev\vue-rethinkdb\bridge
> node server.js

   [Busy] Launching SocketCluster
Tue Jan 22 2019 19:45:54 GMT-0700 (Mountain Standard Time) - info:    !! The sc-hot-reboot plugin is watching for code changes in the D:\dev\vue-rethinkdb\bridge directory
   >> Broker PID: 27272
Tue Jan 22 2019 19:45:55 GMT-0700 (Mountain Standard Time) - info:    >> WorkerCluster PID: 8588
Tue Jan 22 2019 19:45:57 GMT-0700 (Mountain Standard Time) - info:    >> Connecting to RethinkDB...
Tue Jan 22 2019 19:45:57 GMT-0700 (Mountain Standard Time) - info:    >> RethinkDB Connected!
1548211557896 - Origin: Worker (PID 17980)
   [Error] Error: Cannot find module 'uws'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at new SCServer (D:\dev\vue-rethinkdb\bridge\node_modules\socketcluster-server\scserver.js:106:54)
    at Object.module.exports.attach (D:\dev\vue-rethinkdb\bridge\node_modules\socketcluster-server\index.js:65:29)
    at D:\dev\vue-rethinkdb\bridge\node_modules\socketcluster\scworker.js:202:41
1548211557917 - Worker 0 exited - Exit code: 1
Tue Jan 22 2019 19:45:59 GMT-0700 (Mountain Standard Time) - info:    >> Connecting to RethinkDB...
Tue Jan 22 2019 19:45:59 GMT-0700 (Mountain Standard Time) - info:    >> RethinkDB Connected!
[repeatedly fails]
```

**Comment by jaredthirsk** [comment]
[UPDATE: Works on Windows Subsystem for Linux. Good enough for me.]

**Comment by crrobinson14** [comment]
Sorry I didn't reply earlier, my notifications were turned off and I didn't notice this. Glad you were able to sort it out. I'm cleaning up old tickets and will be replacing the SocketCluster bridge with something much simpler and easier to use.

**Comment by jondubois** [comment]
@crrobinson14 You could look at SC v16, it's more like a set of libraries than a monolithic framework (complexity and was a genuine problem before) - v16 is heavily focused around async/await. v16's message order guarantee (e.g. even when you use `await` inside message handlers) could be useful for your use case since you probably often make async database calls from inside your message handlers.

That said, the v16 API is more verbose and can be difficult to get used to (encourages a lot of IIFEs now). If you can get used to it, it should help prevent a lot of hard-to-catch bugs especially race conditions when doing a lot of async processing.

**Comment by crrobinson14** [comment]
@jaredthirsk I still have a love affair with SocketCluster and I think it's a great solution to a lot of needs at that layer. But I also think application developers should be the ones choosing what back-end realtime communications framework they use, and SC could be a barrier for some either looking for a quick win, or trying to understand the moving pieces. It was one more thing to learn. The next version of this module will simplify the server-side component around Primus, which works fine for basic cases, takes very little code to implement, and is easily replaced by those with more advanced needs (and skills).
